import { Activity, Accessibility, Clock3, Puzzle, Chrome, CheckCircle2 } from 'lucide-react';
import { useLucent } from '../../lib/lucent-state';
import ActivityTable from '../components/ActivityTable';
import { Link } from 'react-router-dom';
export default function Dashboard() {
 const { settings, update, events, extensionAvailable } = useLucent();
 const chooseProfile=(profile:'cognitive'|'motor')=>update({profile,enabled:true,cognitive:profile==='cognitive'?{declutter:true,dyslexia:true,readingGuide:false,calmMode:true,readingWidth:true}:{declutter:false,dyslexia:false,readingGuide:false,calmMode:false,readingWidth:false},motor:profile==='motor'?{targets:true,focus:true,shortcuts:true,steadyClick:true,largeCursor:true}:{targets:false,focus:false,shortcuts:false,steadyClick:true,largeCursor:false}});
 const active = [...Object.values(settings.cognitive), ...Object.values(settings.motor)].filter(Boolean).length;
 const minutes = events.length * 3;
 const activities = events.slice(0,5).map((e,i)=>({id:i, website:e.site, page:e.action, feature:e.feature, duration:'Live', time:new Date(e.at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}));
 return <div className="dashboard-page"><div className="dashboard-page-header"><div><p className="dashboard-eyebrow">LIVE ACCESSIBILITY CONTROL</p><h1>Your web, tuned for you.</h1><p>Controls below update your extension immediately when it is connected.</p></div><button aria-pressed={settings.enabled} className={`extension-power ${settings.enabled?'extension-power-on':''}`} onClick={()=>update({enabled:!settings.enabled})}><span className="extension-power-knob"/><span>{settings.enabled?'Lucent is on':'Start Lucent'}</span></button></div>
 <section className="dashboard-panel profile-picker"><div className="dashboard-panel-header"><div><h2>What support do you need today?</h2><p>Pick one profile. The extension shows only that profile’s relevant tools.</p></div></div><div className="profile-options"><button className={settings.profile==='cognitive'?'profile-option selected':'profile-option'} onClick={()=>chooseProfile('cognitive')}><strong>🧠 Cognitive & ADHD</strong><span>Focus support, calmer pages and easier reading.</span></button><button className={settings.profile==='motor'?'profile-option selected':'profile-option'} onClick={()=>chooseProfile('motor')}><strong>🖐 Motor & Tremor</strong><span>Larger targets, keyboard control and steady clicks.</span></button></div></section>
 <section className="dashboard-panel" style={{marginBottom:24}}><div className="dashboard-panel-header"><div><h2><Chrome size={18} style={{verticalAlign:'middle',marginRight:8}}/>Get the Lucent extension</h2><p>Download, unzip, and load it once in Chrome. Your dashboard settings then sync instantly.</p></div><span className={extensionAvailable?'dashboard-status':'dashboard-status dashboard-status-off'}>{extensionAvailable?<><CheckCircle2 size={15}/> Connected</>:'Ready to install'}</span></div><div className="extension-download"><div><strong>Lucent for Chrome</strong><span>Includes the floating bottom-right feature controller.</span></div><a className="extension-download-button" href="/Lucent-extension.zip" download>Download extension .zip</a><Link to="/dashboard/features" className="dashboard-panel-link">Configure features →</Link></div></section>
 <div className="dashboard-stats-grid"><Stat title="Live sessions" value={String(events.length)} description="Recorded by your extension" icon={<Activity size={20}/>}/><Stat title="Active features" value={String(active)} description={settings.enabled?'Applying on websites':'Turn on to apply'} icon={<Accessibility size={20}/>}/><Stat title="Assist time" value={`${minutes}m`} description="Based on actual extension events" icon={<Clock3 size={20}/>}/><Stat title="Current profile" value={settings.profile==='cognitive'?'ADHD':'Motor'} description="Selected during onboarding" icon={<Puzzle size={20}/>}/></div>
 <section className="dashboard-panel" style={{marginTop:24}}><div className="dashboard-panel-header"><div><h2>Live activity</h2><p>Events appear here as you browse with Lucent enabled.</p></div></div>{activities.length?<ActivityTable activities={activities}/>:<div className="dashboard-empty">No browser activity yet. Turn on Lucent, visit a website, and interact normally.</div>}</section></div>;
}
function Stat({title,value,description,icon}:{title:string;value:string;description:string;icon:React.ReactNode}){return <div className="dashboard-stat-card"><div className="dashboard-stat-icon">{icon}</div><span>{title}</span><strong>{value}</strong><small>{description}</small></div>}
