import { GoogleGenAI } from '@google/genai';

export default async function handler(req, res) {
  // Set CORS headers for Chrome Extension
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    return res.status(204).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const apiKey = process.env.GEMINI_API_KEY || '';
  const context = req.body || {};

  if (!apiKey) {
    return res.status(200).json(generateFallback(context));
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const prompt = `
You are an expert Web Accessibility (WCAG 2.2 AAA) AI auditor.
Analyze the following unlabelled interactive elements and images on the webpage "${context.pageTitle || 'Webpage'}" (${context.pageUrl || ''}).
Generate accurate, concise, human-friendly 'aria-label' text for interactive controls (buttons, links) and 'alt' descriptions for images.

Unlabelled Elements:
${JSON.stringify((context.unlabelledElements || []).slice(0, 15), null, 2)}

Images Missing Alt Text:
${JSON.stringify((context.missingAltImages || []).slice(0, 15), null, 2)}

Return strictly valid JSON:
{
  "labels": {
    "<element_id>": "Short action description"
  },
  "imageAlts": {
    "<image_id>": "Accurate alt text under 120 chars"
  },
  "summary": "Brief 1-sentence summary of fixes",
  "confidenceScore": 0.98
}
`;
    const response = await ai.models.generateContent({
      model: 'gemini-1.5-flash',
      contents: prompt,
      config: { responseMimeType: 'application/json' }
    });
    const parsed = JSON.parse(response.text?.trim() || '{}');
    return res.status(200).json({
      labels: parsed.labels || {},
      imageAlts: parsed.imageAlts || {},
      summary: parsed.summary || 'Remediations generated by Gemini 1.5 Flash.',
      confidenceScore: typeof parsed.confidenceScore === 'number' ? parsed.confidenceScore : 0.96
    });
  } catch (err) {
    console.error('Gemini serverless handler error:', err);
    return res.status(200).json(generateFallback(context));
  }
}

function generateFallback(context) {
  const labels = {};
  const imageAlts = {};
  (context.unlabelledElements || []).forEach(el => {
    const hint = el.elementId || el.className || 'control';
    const clean = hint.replace(/[-_]/g, ' ').replace(/[0-9]/g, '').trim();
    labels[el.id] = `Interactive control: ${clean || 'Click to activate'}`;
  });
  (context.missingAltImages || []).forEach(img => {
    imageAlts[img.id] = `Image on ${context.pageTitle || 'webpage'}`;
  });
  return {
    labels,
    imageAlts,
    summary: `Heuristic remediations applied for ${Object.keys(labels).length} controls and ${Object.keys(imageAlts).length} images.`,
    confidenceScore: 0.88
  };
}
